# Generated by Django 4.1.6 on 2023-02-15 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0002_movieorder_movie_movie_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_orders",
            field=models.ManyToManyField(
                related_name="movie",
                through="movies.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
